on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Envs
        run: |
          apt install flatpak flatpak-builder appstream-compose -y
          flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Build
        run: |
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.qq.QQ.yaml
          flatpak build-bundle repo com.qq.QQ.flatpak com.qq.QQ
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-flatpak-qq
          path: |
            *.flatpak
