on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Envs
        run: |
          sudo apt update -y
          sudo apt install flatpak flatpak-builder appstream-compose -y
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Test
        run: |
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo builddir com.qq.QQ.yaml
